name: Testing
on: push

jobs:
  test_project:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8.6
      uses: actions/setup-python@v1
      with:
        python-version: 3.8.6
    - name: Install dependencies and requirements
      run: |
        python -m pip install --upgrade pip
        pip3 install --user selenium
    - name: Prepare selenium
      uses: tomwhross/setup-chromedriver@master
    - name: Run tests
      run: python tests.py

